[package]
name = "euclid"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
rayon = "1.11.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "naive_intersection"
harness = false

[[bench]]
name = "indexed_intersection"
harness = false